export const CONFIG = {
  quality: 'medium',
  worldSize: 420,
  terrainResolution: 192,
  islandCount: 12,
  minIslands: 7,
  minIslandCells: 28,
  maxIslandShare: 0.22,
  crateCount: 5,
  refugeeRange: [8, 20],
  helipadRange: [3, 6],
  minAlt: 0,
  maxAlt: 26,
  pickupAlt: 4,
  landingAlt: 3,
  heliGroundClearance: 0.7,
  safeLandingVSpeed: 10.5,
  hardLandingMinDrop: 8,
  safeLandingHSpeed: 1.2,
  speedLevels: 5,
  speedStep: 6,
  turnDegPerSec: 120,
  heliTilt: {
    maxPitchDeg: 12,
    maxRollDeg: 14,
    response: 8,
  },
  fuelMax: 100,
  refuelPerSec: 20,
  timeLimitSec: 360,
  startupCrateInterval: 0.22,
  startupFuelTickInterval: 0.3,
  fixedDt: 1 / 60,
  camera: { fovDeg: 42, tiltDeg: 45, minTiltDeg: 0, maxTiltDeg: 86, tiltStepDeg: 1, dist: 56, minDist: 32, maxDist: 86 },
  cyclone: { far: 85, mid: 45, near: 22, baseSpeed: 2.4 },
};

export const GAME_NAME = 'Cyclone2026: ZX Rescue';
